### PR TITLE
Handle beta OCP versions

### LINKED ISSUE #980: platform-alteration-ocp-node-os-lifecycle test fails if OCP RC versions are detected
Hi team!
If you check this DCI job: https://www.distributed-ci.io/jobs/00c7beb3-1c61-43e4-90bd-76307b8bee9d/files (check dci-tnf-execution.log for checking the tnf execution), the platform-alteration-ocp-node-os-lifecycle test is failing because, from what I see, is not able to parse correctly an OCP RC version:

```
[38;5;243m------------------------------[0m
[0mplatform-alteration [0m[1mplatform-alteration-ocp-node-os-lifecycle[0m [38;5;204m[common, platform-alteration-ocp-node-os-lifecycle, platform-alteration][0m
[38;5;243m/usr/tnf/tnf-src/cnf-certification-test/platform/suite.go:144[0m
  [1mSTEP:[0m Testing the control-plane and workers in the cluster for Operating System compatibility [38;5;243m@ 04/01/23 05:34:04.03[0m
[37mDEBUG  [0m[Apr  1 05:34:04.030][suite.go: 499] There are 7 nodes to process for Operating System compatibility. 
[37mDEBUG  [0m[Apr  1 05:34:04.030][suite.go: 505] Node master-0 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.030][suite.go: 505] Node master-1 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.030][suite.go: 505] Node master-2 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.031][suite.go: 505] Node worker-0 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.031][suite.go: 534] Comparing RHCOS shortVersion: 4.13.0-rc.2 to openshiftVersion: 4.13.0-rc.2 
  Node worker-0 has been found to be running an incompatible version of RHCOS: 4.13.0-rc.2
[37mDEBUG  [0m[Apr  1 05:34:04.031][suite.go: 505] Node worker-1 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.032][suite.go: 534] Comparing RHCOS shortVersion: 4.13.0-rc.2 to openshiftVersion: 4.13.0-rc.2 
  Node worker-1 has been found to be running an incompatible version of RHCOS: 4.13.0-rc.2
[37mDEBUG  [0m[Apr  1 05:34:04.032][suite.go: 505] Node worker-2 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.032][suite.go: 534] Comparing RHCOS shortVersion: 4.13.0-rc.2 to openshiftVersion: 4.13.0-rc.2 
  Node worker-2 has been found to be running an incompatible version of RHCOS: 4.13.0-rc.2
[37mDEBUG  [0m[Apr  1 05:34:04.032][suite.go: 505] Node worker-3 is running operating system: Red Hat Enterprise Linux CoreOS 413.92.202303281804-0 (Plow) 
[37mDEBUG  [0m[Apr  1 05:34:04.032][suite.go: 534] Comparing RHCOS shortVersion: 4.13.0-rc.2 to openshiftVersion: 4.13.0-rc.2 
  Node worker-3 has been found to be running an incompatible version of RHCOS: 4.13.0-rc.2
  Number of worker nodes running non-RHCOS or non-RHEL based operating systems: 4
  [38;5;9m[FAILED][0m in [It] - /usr/tnf/tnf-src/cnf-certification-test/platform/suite.go:595 [38;5;243m@ 04/01/23 05:34:04.033[0m
[38;5;9m• [FAILED] [0.002 seconds][0m
[0mplatform-alteration [38;5;9m[1m[It] platform-alteration-ocp-node-os-lifecycle[0m [38;5;204m[common, platform-alteration-ocp-node-os-lifecycle, platform-alteration][0m
[38;5;243m/usr/tnf/tnf-src/cnf-certification-test/platform/suite.go:144[0m
```

OCP version used for this deployment is OCP 4.13.0-rc.2

I tried to check the code but I was not able to detect the root cause of the problem, can you please help on this?

### PR DESCRIPTION
**Pull request by sebrandon1**
Resolves #980 

Adds a variable called `ocpBetaVersions` which is just a slice of "major.minor" versions.

Adds a short-circuit func called `BetaRHCOSVersionsFoundToMatch` which will short circuit the `IsRHCOSCompatible` function if we have some beta versions running.

### CODE REVIEW

File: pkg/compatibility/compatibility.go [hunk 1]
```diff
@@ -201,14 +216,23 @@ func IsRHELCompatible(machineVersion, ocpVersion string) bool {
 	return false
 }
 
+func FindMajorMinor(version string) string {
+	splitVersion := strings.Split(version, ".")
+	return splitVersion[0] + "." + splitVersion[1]
+}
+
```
Comment (rdavid) [inline pkg/compatibility/compatibility.go:223]:
```suggestion
func FindMajorMinor(version string) string {
	if splitVersion := strings.Split(version, "."); len(splitVersion) > 1 {
		return splitVersion[0] + "." + splitVersion[1]
	else {
		return splitVersion[0] + ".0"
	}
}
```

**Review by rdavid — APPROVED** [review]

File: pkg/compatibility/compatibility.go [hunk 2]
```diff
@@ -49,6 +50,7 @@ type VersionInfo struct {
 }
 
 var (
+	ocpBetaVersions   = []string{"4.13", "4.14"}
```
Comment (ramperher) [inline pkg/compatibility/compatibility.go:53]: I guess this variable would be updated then these versions beceome GA (or when a new beta OCP version is released), wouldn't it?

**Review by ramperher — APPROVED** [review]

File: pkg/compatibility/compatibility.go (hunk 2 above)
Comment (sebrandon1) [reply pkg/compatibility/compatibility.go:53]: Yeah, unfortunately it's a manual process like the `ocpLifeCycleDates` variable.  Luckily the values don't change often.

File: pkg/compatibility/compatibility.go (hunk 1 above)
Comment (sebrandon1) [reply pkg/compatibility/compatibility.go:223]: I've been thinking about this.  Because the value ".0" would mean an actual dot-zero version exists.  I'm torn.  None of the values in the [rhcos_version_map](https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/platform/operatingsystem/files/rhcos_version_map) are missing their [1] positions right now so I guess we control the inputs in that way.

Comment (sebrandon1) [reply pkg/compatibility/compatibility.go:223]: If we encounter values in the rhcos_version_map in the future that are missing their values I'd say we can edit this at that time.  I'll keep it in mind.  👍

Comment (rdavid) [reply pkg/compatibility/compatibility.go:223]: I like proper error handling, `splitVersion[1]` could panic on certain inputs. Replace `.0` on `.x` or remove it. But the condition is right.
